import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { getServerClient } from "@/lib/supabase/server";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type SitePreferences = {
  theme: "LIGHT" | "DARK" | "PHOTO";
  backgroundTheme: "MURAL" | "HOOP" | "HK";
};

// Thème Sombre/Clair/Photo (SPEC_ECRAN_PROFIL_V0_1 §4, 3e valeur ajoutée le
// 06/08/2026 — cf. migrations 20260806100000/20260806110000) : câblage
// explicitement laissé en attente par app/tokens.css pour le thème (« la
// bascule est un lot séparé »). Lus ENSEMBLE ICI (racine, hors des deux
// route groups, une seule requête) car [data-theme="..."] et [data-bg="..."]
// s'appliquent à TOUT le site, visiteur non connecté inclus (/login,
// /leaderboard...). Un visiteur sans session reste sur les défauts
// (DARK / MURAL, mêmes valeurs que les défauts colonne ET CSS sur :root) —
// aucune préférence à lire pour lui.
async function getSitePreferences(): Promise<SitePreferences> {
  const DEFAULTS: SitePreferences = { theme: "DARK", backgroundTheme: "MURAL" };

  const supabase = await getServerClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) return DEFAULTS;

  const { data } = await supabase
    .from("users")
    .select("theme_preference, background_theme")
    .eq("id", user.id)
    .single<{ theme_preference: "LIGHT" | "DARK" | "PHOTO"; background_theme: "MURAL" | "HOOP" | "HK" }>();

  if (!data) return DEFAULTS;
  return { theme: data.theme_preference, backgroundTheme: data.background_theme };
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { theme, backgroundTheme } = await getSitePreferences();

  return (
    <html
      lang="en"
      data-theme={theme === "LIGHT" ? "light" : theme === "PHOTO" ? "photo" : undefined}
      data-bg={theme === "PHOTO" && backgroundTheme !== "MURAL" ? backgroundTheme.toLowerCase() : undefined}
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
