import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { getServerClient } from "@/lib/supabase/server";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Thème clair/sombre (SPEC_ECRAN_PROFIL_V0_1 §4) : câblage explicitement
// laissé en attente par app/tokens.css (« la bascule est un lot séparé »).
// Lu ICI (racine, hors des deux route groups) car [data-theme="light"]
// s'applique à TOUT le site, visiteur non connecté inclus (/login,
// /leaderboard...). Un visiteur sans session reste en DARK (défaut colonne
// ET défaut CSS sur :root) — aucune préférence à lire pour lui.
async function getTheme(): Promise<"LIGHT" | "DARK"> {
  const supabase = await getServerClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) return "DARK";

  const { data } = await supabase
    .from("users")
    .select("theme_preference")
    .eq("id", user.id)
    .single<{ theme_preference: "LIGHT" | "DARK" }>();

  return data?.theme_preference ?? "DARK";
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const theme = await getTheme();

  return (
    <html
      lang="en"
      data-theme={theme === "LIGHT" ? "light" : undefined}
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
